version: "3.8"

services:
  # API 서버 (개발 모드)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./api:/app
      - /app/node_modules
    command: ["pnpm", "run", "dev"]
    ports:
      - "8137:3000"

  # 웹 애플리케이션 (개발 모드)
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    environment:
      - REACT_APP_API_URL=http://10.4.0.33:8137
      - REACT_APP_ENV=development
    volumes:
      - ./web:/app
      - /app/node_modules
    command: ["npm", "start"]
    ports:
      - "8138:3000"
    stdin_open: true
    tty: true
